services:
  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "app_user"
      POSTGRES_DB: "app_db"
    ports: 
      - "5432:5432"
  
  django:
    build: .
    command: /app/wait-for-postgres.sh python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app  # Sincroniza o código local com o contêiner
    ports:
      - "8000:8000"
    depends_on:
      - postgres
