test:
	ls

updatebd:
	python manage.py makemigrations
	python manage.py migrate

run:
	python manage.py runserver

requeriments:
	pip freeze > requirements.txt

pipupdate:
	python.exe -m pip install --upgrade pip
	pip install -r requirements.txt