# Generated by Django 5.1.3 on 2024-11-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('escolaridade', models.CharField(max_length=100)),
                ('habilidades', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('disponivel', 'disponivel'), ('indisponivel', 'indisponivel')], default='disponivel', max_length=100)),
                ('data_atualizacao', models.DateField()),
            ],
        ),
    ]
